# Generated by Django 3.1.7 on 2021-04-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210409_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default='12:00:00', verbose_name='Event Time'),
        ),
    ]
